version: '3.8'

services:
  oracle-xe:
    image: gvenzl/oracle-xe:21-slim
    container_name: oracle-xe
    environment:
      ORACLE_PASSWORD: dreams_pass
      ORACLE_USER: dreams_user
    ports:
      - "1521:1521"

  dreams-spring:
    build:
      context: .
    container_name: dreams-spring
    environment:
      SPRING_DATASOURCE_URL: jdbc:oracle:thin:@oracle-xe:1521
      SPRING_DATASOURCE_USERNAME: dreams_user
      SPRING_DATASOURCE_PASSWORD: dreams_pass
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    ports:
      - "8080:8080"
    depends_on:
      - oracle-xe